server {
    listen 80;
    server_name localhost;

    # --- ADMINISTRADOR (.NET Core 10) ---
    location /admin {
        # Cambiamos de 80 a 8080
        proxy_pass http://dotnet-app:8080; 
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    # --- BÚSQUEDA (FastAPI) ---
    location /api/search {
        # FastAPI usa el 8000
        proxy_pass http://python-app:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # --- AUDITORÍA (PHP Laravel) ---
    # Como usas PHP-FPM, la configuración es un poco diferente
    location / {
        root /var/www/html/public;
        index index.php;
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        root /var/www/html/public;
        fastcgi_pass php-app:9000; # PHP-FPM habla por el 9000
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }
    
}